version: '3.9'
services:
    db:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: actix
            POSTGRES_USER: actix
            POSTGRES_DB: actix
        volumes: 
        - ./postgres:/var/lib/postgresql/data
        ports:
        - "5432:5432"
    redis:
      restart: always
      image: "redis:alpine"
      ports:
      - "6379:6379"
networks:
  default:
    external:
      name: main