name: Build API

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  STOP_BUILD_PROTO: true
  IMAGE_NAME: age_info_api

jobs:
  build:
    
    runs-on: ubuntu-latest

    name: build release
    env:
      SQLX_OFFLINE: true
    
    defaults:
      run:
        working-directory: ./api
    container:
      image: clux/muslrust
    
    steps:
    - uses: actions/checkout@v2
    - name: Link to predefined musl toolchain
      run: |
          ln -s /root/.cargo $HOME/.cargo
          ln -s /root/.rustup $HOME/.rustup
    
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: api_x86_musl
        path: |
          ./api/target/x86_64-unknown-linux-musl/release/api
          ./api/config
          ./api/proto
          ./api/Dockerfile
          - name: Build image
    
  build_docker:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    name: build docker image
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        # Artifact name
        name: api_x86_musl
    - name: show files
      run: ls -R
    - name: build docker
      run: docker build ./api --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.UPLOAD_PACKAGE_SECRET }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
