name: Build API

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  STOP_BUILD_PROTO: true
jobs:
  build:
    
    runs-on: ubuntu-latest
    name: build release
    env:
      SQLX_OFFLINE: true
    defaults:
      run:
        working-directory: ./api
    container:
      image: clux/muslrust
    steps:
    - uses: actions/checkout@v2
    - name: Link to predefined musl toolchain
      run: |
          ln -s /root/.cargo $HOME/.cargo
          ln -s /root/.rustup $HOME/.rustup
    
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: api_x86_musl
        path: |
          ./api/target/x86_64-unknown-linux-musl/release/api
          ./api/config
          ./api/proto
