name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    runs-on: ubuntu-latest
    name: build release
    env:
      OPENSSL_SSL_LIBRARIES: /usr/local/ssl/lib
    defaults:
      run:
        working-directory: ./crawler
    steps:
    - uses: actions/checkout@v2
    - name: install openssl
      run: |
        sudo apt install libssl-dev -y
        sudo apt install pkg-config -y
    - name: prepare
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl 
    - uses: actions/upload-artifact@v2
      with:
        name: Crawler
        path: target/x86_64-unknown-linux-musl/build
 
