name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    runs-on: ubuntu-latest
    name: build release
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: rustup target add x86_64-unknown-linux-musl
    - name: cd into directory
      run: cd ./crawler
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl 
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: target/x86_64-unknown-linux-musl/build
 
